var QB_FORM_ID = "QB_FORM_ID";
var QB_CORRECT_ANSWERS = "QB_CORRECT_ANSWERS";

var QB_OPT_IS_QUIZ = "QB_OPT_IS_QUIZ";
var QB_OPT_ONE_ANS_PER_USER = "QB_OPT_ONE_ANS_PER_USER";
var QB_OPT_LOGIN_REQ ="QB_OPT_LOGIN_REQ";
var QB_OPT_SHUFFLE = "QB_OPT_SHUFFLE";
